### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by cryptoquick** [strict-types/strict-types#6]
On the call, I believe you called this "strict dump" with a P, but here, it's spelled "strict dumb", with a B:
https://github.com/strict-types/strict-types/blob/8f397c37fe12ed08605802f4080b2917a6daba85/src/ast/id.rs#L53-L55

**Comment by dr-orlovsky** [comment]
It should be strict dum_b_, since it produces a value of the datatype which should be used as a dumb (i.e. not a memory dump, but a sort of `default` value with no meaning).
